services:
  proxy:
    container_name: camera-marketplace-proxy
    restart: always
    image: ghcr.io/nicrozj/camera-marketplace-proxy:latest
    networks:
      - docker_network
    ports:
      - 9080:80
      - 9443:443
    volumes:
      - ./data/caddy:/data/caddy
      
networks:
  docker_network:
    external: true