version: '3.8'

services:
  proxy:
    image: ghcr.io/nicrozj/camera-marketplace-proxy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  php:
    image: ghcr.io/nicrozj/camera-marketplace-php:latest
    container_name: php-container
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=marketplace
      - DB_USER=root
      - DB_PASSWORD=root12345

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: marketplace
      MYSQL_USER: zhorkinigor
      MYSQL_PASSWORD: root12345
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  caddy_data:
  caddy_config: