services:
  proxy:
    container_name: camera-marketplace-proxy
    restart: always
    image: ghcr.io/nicrozj/camera-marketplace-proxy:latest
    networks:
      - docker_network
    volumes:
      - ./data/caddy:/data/caddy

  php:
    container_name: php-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: php-runner  # Используем таргет php-runner из Dockerfile
    volumes:
      - ./backend:/web/php
    environment:
      - PHP_BASE_DIR=/web/php
      - DB_HOST=mysql
      - DB_DATABASE=marketplace
      - DB_USER=root
      - DB_PASSWORD=root12345
    networks:
      - docker_network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: marketplace
      MYSQL_USER: zhorkinigor
      MYSQL_PASSWORD: root12345
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - docker_network

volumes:
  mysql_data:

networks:
  docker_network:
    external: true
