services:
  proxy:
    container_name: caddy-proxy
    build:
      context: .
      target: caddy-runner
    volumes:
      - ./data/caddy:/data/caddy
    ports:
      - 80:80

  php:
    container_name: php-container
    restart: always
    build:
      context: .
      target: php-runner
    volumes:
      - ./backend:/web/php
    environment:
      - PHP_BASE_DIR=/web/php
      - DB_HOST=mysql
      - DB_DATABASE=marketplace
      - DB_USER=root
      - DB_PASSWORD=root12345

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: marketplace
      MYSQL_USER: zhorkinigor
      MYSQL_PASSWORD: root12345
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
