name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push images
        run: |
          # Собираем и пушим оба образа
          docker buildx build \
            --file Dockerfile \
            --tag ghcr.io/nicrozj/camera-marketplace-proxy:latest \
            --target proxy \
            --push \
            .

          docker buildx build \
            --file Dockerfile \
            --tag ghcr.io/nicrozj/camera-marketplace-php:latest \
            --target php \
            --push \
            .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_ADDR }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            # Добавляем аутентификацию на сервере
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd camera-marketplace
            docker compose pull
            docker compose up -d